modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/JayZX535/prehistoric-variants-mc/issues"
[[mods]]
modId="prehistoricvariants"
version="1.0"
displayName="Prehistoric Variants"
logoFile="prehistoricvariants.png"
#credits=""
authors="JayZX535"
displayTest="IGNORE_SERVER_VERSION"
description='''A mod that adds additional variant condition types for Fossils & Archeology: Revival!

Dinosaurs and other prehistoric creatures are added by Fossils & Archeology: Revival and are NOT from this mod!  All that Prehistoric Variants does is add two additional cases in which variants can be selected, and a few extra variants to go with them.  If you encounter an issue with random or biome based variant spawning, please refer to the Prehistoric Variants issue tracker, NOT F&A's!'''
[[dependencies.prehistoricvariants]]
modId="fossil"
mandatory=true
versionRange="[9.1.4.0,)"
ordering="NONE"
side="BOTH"
